[profile.dev]
opt-level = 0
codegen-units = 255

[workspace]
members = ["rlang", "rl"]
resolver = "3"

[profile.release]
strip=true
lto=true
panic="abort"
opt-level = "z"
codegen-units = 1
incremental = true
